### ISSUE TITLE
Conveniencia de un GenericDto que substituya el zoológico de DTO's en Opendata

### ISSUE THREAD

**Issue by R-Torrent** [IT-Academy-BCN/BusinessAssistantBCN-backend#68]
Opendata

Hasta la fecha, todos los DTOs con la sola excepción del DTO de testeo (Star Wars) tienen los mismos campos. ¿Hay algún mótivo práctico para mantener BigMallsDto, MarketFairsDto, CommercialGalleriesDto, etc. si el formato de las respuestas no varía? (Por otro lado, existen pequeñas inconsistencias en algunos tipos.) De igual manera, ¿para qué todos los servicios IDÉNTICOS que atienden a estos DTOs? Si, por algún motivo que desconozco, conviene mantener la distinción entre todas estas clases, ¿no sería mejor tener un DTO papá del que todos hereden por igual?

Ahora mismo estoy realizando el testeo del controlador. Con la petición BigMalls testeada, debería encontrarme con un «hecho uno, hecho todos». Bastaría una simple parametrización con la dirección URL para automatizarlo pues, ¡oh sorpresa!, los ensayos son idénticos para cada petición. Pero no, debo parametrizar también cada una de las clases. Va a quedar muy feo…

**Comment by jonatanvicente** [comment]
La aproximación que indicas es valorable, teniendo en cuenta lo siguiente:

- Todas las API consultadas tienen el mismo formato, como indicas. Es posible heredar de un mismo objeto y utilizar más el polimorfismo (con atributos globales), pero esto nos complica en tiempo de ejecución. Es mucho más fácil hacer segumiento de errores teniendo los objetos específicos de cada enpoint y, si el proveedor cambia algo, tan sólo cambiamos el atributo que corresponde sin impactar a la definición de los demás. Puede parecer redundante (lo es, de hecho), pero simplifica mucho la tarea en tiempos de ejecución (aunque no tanto en desarrollo).

- No obstante, observarás que la aproximación que indicas (acertada) la empleamos en el desarrollo de la mayoría de funcionalidades. Mantenemos los servicios diversificados por idéntica cuestión, aunque quizá en un futuro los refactoricemos para simplificar.

Mil gracias por el aporte, Roger  ;)
